version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  web:
    restart: always
    build: .
    # Assigns a name for the container. If no name is specified,
    # Docker will assign the container a random name
    container_name: drf_app
    env_file:
      - .env
    # Mount the container `/drf` folder to the a `src` folder in the location
    # of the Dockerfile on the host machine.
    volumes:
      - ./src:/drf
      - ./static/static_root/:/app/static/static_root

    command: gunicorn leaveproject.wsgi:application -b 0.0.0.0:8000
    # Map port 8000 to port 8000 so that we can access the application on
    # our host machine by visiting 127.0.0.1:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    restart: always
    build: .
    ports:
      - "80:80"
    links:
      - web:web
    volumes:
    - ./static/static_root/:/static

volumes:
  pgdata: