version: '3'

# Build a multiservice arhitecture.
services:
  data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: "true"

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    env_file:
      - .env
    expose:
      - "5432"

  web:
    restart: always
    build: .
    # Assigns a name for the container. If no name is specified,
    # Docker will assign the container a random name
    container_name: drf_app
    env_file:
      - .env
    # Mount the container `/drf` folder to the a `src` folder in the location
    # of the Dockerfile on the host machine.
    volumes:
      - ./src:/drf

    command: gunicorn leaveproject.wsgi:application -b 0.0.0.0:8000
    # Map port 8000 to port 8000 so that we can access the application on
    # our host machine by visiting 127.0.0.1:8000
    ports:
      - "8000:8000"

  nginx:
    restart: always
    build: .
    ports:
      - "80:80"
    links:
      - web:web

volumes:
  pgdata: